Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.provision :shell, :path =&gt; "provision.sh"
  config.vm.synced_folder ".", "/vagrant", :mount_options =&gt; ['dmode=777,fmode=666']
end
